### ISSUE TITLE
 InvalidArgumentException    Invalid preset.

### ISSUE THREAD

**Issue by magarrent** [InfyOmLabs/laravel-ui-coreui#5]
I've just insalled the package in a fresh laravel 7:

`composer require infyomlabs/laravel-ui-adminlte:^2.0`

![image](https://user-images.githubusercontent.com/6561770/93202346-d750d800-f752-11ea-8fdf-8dd49a61cd66.png)

**Comment by ShaileshInfyom** [comment]
![image](https://user-images.githubusercontent.com/28335166/151549752-62e019cc-b383-4416-b81b-e64a4e6c5bd0.png)
This issue is not produced anymore.

Feel free to re-open the issue with more details if you are still facing this issue.
