### ISSUE TITLE
php 8 compatibility

### ISSUE THREAD

**Issue by massimocolella** [InfyOmLabs/laravel-ui-coreui#7]
Hi there,
is there a roadmap to get php 8 compatibility for this package?
Thanks in advance.

**Comment by rhoyle** [comment]
Same Question as above also will you be updating the Laravel template to us Laravel v8.42.0  with php 8 ?

**Comment by ShaileshInfyom** [comment]
![image](https://user-images.githubusercontent.com/28335166/151542029-23c89dfa-dea7-4b31-a3d4-446ed9624ab8.png)
@massimocolella @rhoyle PHP 8 support added. 

use following command for installation 
![image](https://user-images.githubusercontent.com/28335166/151542152-219bd69f-85e9-415a-8e9e-5942fa785581.png)

Feel free to re-open the issue with more details if you are still facing this issue.
